apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: github-listener
    name: github-listener
  spec:
    replicas: 1
    selector:
      app: github-listener
      deploymentconfig: github-listener
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: github-listener
          deploymentconfig: github-listener
      spec:
        containers:
        - name: github-listener
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          securityContext:
             privileged: false
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - github-listener
        from:
          kind: ImageStreamTag
          name: github-listener:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: github-listener
      deploymentconfig: github-listener
    name: github-listener
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: github-listener
      deploymentconfig: github-listener
